name: BicepWorkflow-test

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  DEV-deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Bicep files
      run: |
        az bicep lint -f ./bicep/network/main-test.bicep
    - name: Validate Bicep files
      run: |
        az bicep build -f ./bicep/network/main-test.bicep

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy Bicep using Azure CLI
      run: |
        az deployment group create --name ${{ github.run_number }} \
           --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
           --template-file ./bicep/network/main-test.bicep
    
  PROD-deploy:
    runs-on: ubuntu-latest
    environment: PROD
    needs: DEV-deploy
    steps:
    - uses: actions/checkout@v4
    - name: run a script
      run: |
        echo "This is a PROD environment deployment"