name: BicepWorkflow

on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
env:
    AZURE_RESOURCEGROUP_NAME: rg-dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set environment specific variables
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ "${{ github.event.inputs.env }}" == "prod" ]; then
            echo "AZURE_RESOURCEGROUP_NAME=rg-prod" >> $GITHUB_ENV
          else
            echo "AZURE_RESOURCEGROUP_NAME=rg-dev" >> $GITHUB_ENV
          fi
        elif [ "${{ github.event_name }}" == "push" ]; then
          # Default to development environment on push
          echo "AZURE_RESOURCEGROUP_NAME=rg-dev" >> $GITHUB_ENV
        fi
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v2
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./bicep/network/main.bicep
        parameters: adminPassword=${{ secrets.VM_PASSWORD }}
  